import Head from "next/head";
import React from "react";
import styles from "./Layout.module.css";

interface LayoutProps {}

export const Layout = ({ children }: React.PropsWithChildren<LayoutProps>) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.root}>{children}</main>
    </>
  );
};

export default Layout;
